#!/usr/bin/python
# coding=utf-8
# This file is part of TVHeadend Script EPG Grabber

# This script will work on Debian, Ubuntu and probably other distros
# of the same families, although no support is offered for them. It isn't
# bulletproof but it will probably work if you simply want to setup a Stalker WM Portal on
# your Debian/Ubuntu box. It has been designed to be as unobtrusive and
# universal as possible.

# This is a free shell script under GNU GPL version 3.0 or above
# Copyright (C) 2017 LinuxHelps project.
# Feedback/comment/suggestions : https://linuxhelps.net/
# Author Ivan Bachvarov a.k.a SlaSerX



import os
import gzip
import requests
from StringIO import StringIO
from optparse import OptionParser

headerdesktop = {"User-Agent": "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)",
                 "Accept-Language": "it"}
timeoutconnection = 10

parser = OptionParser(version="%prog 1.0b")
parser.add_option("-d","--description", action="store_true",dest="description",default=False, help="Prints the description of this script")
parser.add_option("-c","--capabilities", dest="capabilities", action="store_true" ,help="Not sure what this is - but saw it in tv_grab_file.", default=False)
(options, args) = parser.parse_args()

if options.description is False and options.capabilities is False:
    url = "http://epg.kodibg.org/epg.xml.gz"
    
    # Scarico il file GZIP
    page = requests.get(url, headers=headerdesktop, timeout=timeoutconnection, stream=True)
    compressedFile = StringIO()
    compressedFile.write(page.content)
    compressedFile.seek(0)
    
    # Decomprimo il file GZIP
    decompressedFile = gzip.GzipFile(fileobj=compressedFile, mode='rb')
    
    file_content = decompressedFile.read()
        
    print file_content
elif options.description is True:
    print "TV Grab by URL"
elif options.capabilities is True:
print "baseline"
